remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache  #required by minimal-mistakes
minimal_mistakes_skin: "dark"
title: "Keikai Documentation"

search: true

defaults:
  - scope:
      path: "docs/dev-ref"
    values:
      layout: single
      comments: true
      sidebar:
        nav: "devRef"
      toc: true
      classes: wide


#repository: "username/repo-name"
#logo: "/assets/images/88x88.png"
