remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache  #required by minimal-mistakes
  - jekyll-paginate
minimal_mistakes_skin: "dirt"
title: ""

search                    : true
search_full_content       : true
#  Lunr search only indexes collection documents e.g. posts or any custom collections you have. It does not currently index site.pages.';
search_provider: google
google:
  search_engine_id: 014994008257058938644:cb7qedcky7m


analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-116749276-1"
    anonymize_ip: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      toc: true
      comments: true
      share: true
  - scope:
      path: "dev-ref"
    values:
      sidebar:
        nav: "devRef"
  - scope:
      path: "tutorial"
    values:
      sidebar:
        nav: "tutorial"

comments:
  provider: "disqus"
  disqus:
    shortname: "keikai-doc"
# disqus admin is hawkchen@potix.com
    
#repository: "username/repo-name"
#logo: "/assets/images/88x88.png"
