remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
minimal_mistakes_skin: "dark"
title: "Keikai Documentation"

search: true

#repository: "username/repo-name"
#logo: "/assets/images/88x88.png"
