remote_theme: "mmistakes/minimal-mistakes@4.15.2"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache  #required by minimal-mistakes
  - jekyll-paginate
minimal_mistakes_skin: "dirt"
title: "Keikai Documentation"

search                    : true
search_full_content       : true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-116749276-1"
    anonymize_ip: true

defaults:
  - scope:
      path: "docs"
    values:
      layout: single
      share: true
  - scope:
      path: "docs/dev-ref"
    values:
      layout: single
      comments: true
      sidebar:
        nav: "devRef"
      toc: true
      classes: wide


#repository: "username/repo-name"
#logo: "/assets/images/88x88.png"
